export const TOGGLE_ASSIDE = 'TOGGLE_ASSIDE';

export const GET_BRANCHES = 'GET_BRANCHES';
export const GET_BRANCHES_FOR_MAP = 'GET_BRANCHES_FOR_MAP';
export const GET_BRANCHES_SEARCH = 'GET_BRANCHES_SEARCH';
export const GET_BRANCH_TYPES = 'GET_BRANCH_TYPES';

export const GET_SERVICES = 'GET_SERVICES';

export const GET_LOCALITIES = 'GET_LOCALITIES';

export const GET_TRACKING_INFO = 'GET_TRACKING_INFO';
export const TOGGLE_TRACKING_TTN = 'TOGGLE_TRACKING_TTN';