export const FETCH_METHOD_ARRAY_START = 'FETCH_METHOD_ARRAY_START'
export const FETCH_METHOD_ARRAY_SUCCESS = 'FETCH_METHOD_ARRAY_SUCCESS'
export const FETCH_METHOD_ARRAY_FAILURE = 'FETCH_METHOD_ARRAY_FAILURE'