export const PRINT_GLOBAL_PROPS = "PRINT_GLOBAL_PROPS";

export const SCREEN_RESIZE = "SCREEN_RESIZE";
export const ACCEPT_COOKIES = "ACCEPT_COOKIES";

export const BRANCH_TYPES_LOADING = "BRANCH_TYPES_LOADING";
export const BRANCH_TYPES_LOADED = "BRANCH_TYPES_LOADED";
export const BRANCH_TYPES_ERROR = "BRANCH_TYPES_ERROR";
export const BRANCH_TYPES_CLEAR = "BRANCH_TYPES_CLEAR";

export const SERVICES_LOADING = "SERVICES_LOADING";
export const SERVICES_LOADED = "SERVICES_LOADED";
export const SERVICES_ERROR = "SERVICES_ERROR";
export const SERVICES_CLEAR = "SERVICES_CLEAR";

export const TRACKING_LOADING = "TRACKING_LOADING";
export const TRACKING_LOADED = "TRACKING_LOADED";
export const TRACKING_ERROR = "TRACKING_ERROR";
export const TRACKING_CLEAR = "TRACKING_CLEAR";

export const TRACKING_HISTORY_LOADING = "TRACKING_HISTORY_LOADING";
export const TRACKING_HISTORY_LOADED = "TRACKING_HISTORY_LOADED";
export const TRACKING_HISTORY_ERROR = "TRACKING_HISTORY_ERROR";
export const TRACKING_HISTORY_CLEAR = "TRACKING_HISTORY_CLEAR";

export const BRANCHES_LOADING = "BRANCHES_LOADING";
export const BRANCHES_LOADED = "BRANCHES_LOADED";
export const BRANCHES_ERROR = "BRANCHES_ERROR";
export const SEARCH_BRANCHES = "SEARCH_BRANCHES";
export const BRANCHES_CLEAR = "BRANCHES_CLEAR";
export const BRANCHES_TOGGLE_PAGE = "BRANCHES_TOGGLE_PAGE";

export const BRANCHES_LOCATOR_LOADING = "BRANCHES_LOCATOR_LOADING";
export const BRANCHES_LOCATOR_LOADED = "BRANCHES_LOCATOR_LOADED";
export const BRANCHES_LOCATOR_ERROR = "BRANCHES_LOCATOR_ERROR";
export const BRANCHES_LOCATOR_CLEAR = "BRANCHES_LOCATOR_CLEAR";

export const LOCALITIES_LOADING = "LOCALITIES_LOADING";
export const LOCALITIES_LOADED = "LOCALITIES_LOADED";
export const LOCALITIES_ERROR = "LOCALITIES_ERROR";
export const LOCALITIES_CLEAR = "LOCALITIES_CLEAR";
export const LOCALITIES_TOGGLE_REGION = "LOCALITIES_TOGGLE_REGION";
